language: ruby
rvm:
- 2.0.0
env:
- DB=sqlite
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- rake db:test:prepare
- rake db:seed
- rake
deploy:
  provider: heroku
  app: onebacklog
  api_key:
    secure: CSmgnjpNNXUbn85g0480lsjULDKjQqbzUpOnHiDisgN0MxLIXfzMd9nBjudCKkcoeYgOINxzm56JNBbQh554zHLQM+kwlPdvSRBwoWtJCK5mstvbUb0ZiNpfS7alsrZbhR384dUd2vKSzsAsXb3WZsQ5cCJeBoN8XVSHKv3Q0BM=
  run: "rake db:migrate"
