language: ruby
rvm:
- 2.0.0
env:
- DB=postgres
before_script:
- travis_retry npm install
- ./script/bower_install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- rake db:test:prepare
- cp config/database.travis.yml config/database.yml
- psql -c 'create database onebacklog_test' -U postgres
script:
- rake
deploy:
  provider: heroku
  strategy: git
  app: onebacklog
  api_key:
    secure: CSmgnjpNNXUbn85g0480lsjULDKjQqbzUpOnHiDisgN0MxLIXfzMd9nBjudCKkcoeYgOINxzm56JNBbQh554zHLQM+kwlPdvSRBwoWtJCK5mstvbUb0ZiNpfS7alsrZbhR384dUd2vKSzsAsXb3WZsQ5cCJeBoN8XVSHKv3Q0BM=
  run: "rake db:migrate"
