language: ruby
rvm:
- 2.0.0
env:
- DB=sqlite
before_script:
- npm install -g bower
- rake bower:install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- rake db:test:prepare
script:
- rake
deploy:
  provider: heroku
  strategy: git
  app: onebacklog
  api_key:
    secure: CSmgnjpNNXUbn85g0480lsjULDKjQqbzUpOnHiDisgN0MxLIXfzMd9nBjudCKkcoeYgOINxzm56JNBbQh554zHLQM+kwlPdvSRBwoWtJCK5mstvbUb0ZiNpfS7alsrZbhR384dUd2vKSzsAsXb3WZsQ5cCJeBoN8XVSHKv3Q0BM=
  run: "rake db:migrate"
